# Generated by Django 6.0.4 on 2026-04-09 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.course'),
        ),
        migrations.AddField(
            model_name='admissiondocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admission.admissionapplication'),
        ),
        migrations.AddField(
            model_name='admissionfeepayment',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='admission.admissionapplication'),
        ),
        migrations.AddField(
            model_name='meritlist',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='meritlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_lists', to='core.course'),
        ),
        migrations.AlterUniqueTogether(
            name='meritlist',
            unique_together={('course', 'academic_year')},
        ),
    ]
