# Generated by Django 5.2.13 on 2026-05-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
    ]
